### ISSUE TITLE
Xcode error : overriding declaration requires an 'override' keyword

### ISSUE THREAD

**Issue by fmutin-positivethinking** [Scandit/scandit-react-native-datacapture-barcode#1]
My application build fails because the keyword 'override' is missing on 'invalidate' functions in files :

- /node_modules/scandit-react-native-datacapture-barcode/ios/Sources/BarcodeCapture/ScanditDataCaptureBarcodeCapture.swift at 33:16
- /node_modules/scandit-react-native-datacapture-barcode/ios/Sources/BarcodeTracking/ScanditDataCaptureBarcodeTracking.swift at 88:16

I am using Xcode 12.4 and Scandit 6.7.2.

Do you have a solution to my problem?
Thanks

**Comment by ScanditSupport** [comment]
Hi @fmutin-positivethinking, we're not aware of a generic issue. Would you mind reaching out to support.scandit.com with a short description of how to reproduce it as well as your relevant individual config (e.g. react native version)?

Best regards
Scandit Support
