### ISSUE TITLE
Error on React Native 0.64

### ISSUE THREAD

**Issue by congduong97** [Scandit/scandit-react-native-datacapture-barcode#2]
I cant use this lib in react native 0.64, Application is error in the first time running. It doesnt show scan box and screen is dark 
![Screen Shot 2021-08-20 at 15 58 31](https://user-images.githubusercontent.com/39731881/130208960-5feaac2d-b38b-406f-a377-ff66dc51d31f.png)

**Comment by ScanditSupport** [comment]
@congduong97 is seems like you're running the application on a simulator which doesn't have a camera and result in a black camera preview. 

In case you still have issues in getting it running on a device, please reach out to use directly via 
https://support.scandit.com/ 

Best regards
Scandit Support
