### ISSUE TITLE
Support for react 17.x

### ISSUE THREAD

**Issue by 4iAmAve** [Scandit/scandit-react-native-datacapture-barcode#7]
Hi,

this is a simple one. For a version bump in our application, we would like to bump react to 17.0.1. However, we are also using this module. Since this is pinned to 16.x we are blocked in our efforts.

Therefore, please provide a new version with react 17.x as dependency. Or at least >= 16.8.0

Thank you in advance.

Regards

**Comment by ScanditSupport** [comment]
Hi @4iAmAve,

React 17 will be supported in the next public 6.11 release.
In case you have more detailed questions, please feel free to reach out to us directly:
[Submit a request – Frequently Asked Questions (FAQ) ](https://support.scandit.com/hc/en-us/requests/new)

**Comment by 4iAmAve** [comment]
Hi @ScanditSupport 
Thanks for the information. Is there an ETA for the release?

**Comment by ScanditSupport** [comment]
Hi @4iAmAve 

Production 6.11 should release mid-February.

Do not hesitate to reach out to us if you have any additional questions.

**Comment by 4iAmAve** [comment]
Thanks a lot. Will do.
